spring.application.name=backend
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/megaecuafarma
spring.data.mongodb.database=megaecuafarma

# Server Port
server.port=8080

# Logging (opcional, para ver qué pasa)
logging.level.org.springframework.data.mongodb=DEBUG